### ISSUE TITLE
Missing module `grp`, running on Windows

### ISSUE THREAD

**Issue by ArneBachmannDLR** [willmcgugan/terminal-tree#4]
```
H:\>uvx --from git+https://github.com/willmcgugan/terminal-tree.git --python 3.12 -q terminal-tree
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\XXX\AppData\Local\uv\cache\archive-v0\KpHRQoGeLxWdx5l4wnNB6\Scripts\terminal-tree.exe\__main__.py", line 5, in <module>
  File "C:\Users\XXX\AppData\Local\uv\cache\archive-v0\KpHRQoGeLxWdx5l4wnNB6\Lib\site-packages\tree.py", line 10, in <module>
    import grp
ModuleNotFoundError: No module named 'grp'
```

**Comment by sehHeiden** [comment]
Got the same error with python 3.12 and 3.13

**Comment by peachboy0** [comment]
> Got the same error with python 3.12 and 3.13

This is a problem only on Windows :)

#### `grp.pyi`
```python
# This is the whole file, if anything...

import sys
from _typeshed import structseq
from typing import Any, Final, final

if sys.platform != "win32":
    @final
    class struct_group(structseq[Any], tuple[str, str | None, int, list[str]]):
        if sys.version_info >= (3, 10):
            __match_args__: Final = ("gr_name", "gr_passwd", "gr_gid", "gr_mem")

        @property
        def gr_name(self) -> str: ...
        @property
        def gr_passwd(self) -> str | None: ...
        @property
        def gr_gid(self) -> int: ...
        @property
        def gr_mem(self) -> list[str]: ...

    def getgrall() -> list[struct_group]: ...
    def getgrgid(id: int) -> struct_group: ...
    def getgrnam(name: str) -> struct_group: ...
```
